-- DDL --
-- SQL SERVER REPLICATION --> Bir yerdeki sunucu ile başka sunucu arası veri transferi/Bir verinin farklı konumlardaki sunucularda tutulması
-- SQL RDBMS -->İlişkisel Veritabanı Yönetim Sistemi
-- MasterDB --> Sistem conf/kullanıcılar ve yetkileri/Sistem Dosyaları/Erişim yetkileri/Temel conf
-- ModelDB --> Şablon veritabanı/Her oluşturulacak veritabanı ModelDB'nin bir kopyası
-- MsDB --> Periyodik olarak çalıştırılam her türlü işlem burada tutulur(joblar,schedulelar,alertler)
-- TempDB --> Geçici tabloların oluşturulduğu işlemler burada gerçekleşir/Aggregation işlemler(by,order by,sum,count,max, min gibi)
-- DDL Commands --> CREATE / ALTER / DROP / TRUNCATE
CREATE DATABASE TEST -- Database oluştur
DROP DATABASE TEST --- Database sil
CREATE TABLE ISIMLER (ID INT IDENTITY(1,1),ISIM VARCHAR(20)) -- Tablo oluştur
INSERT INTO ISIMLER(ISIM)VALUES('MEMET') -- kayıt gir
SELECT*FROM ISIMLER -- tablodaki verilerin hepsini çağır
DROP TABLE ISIMLER -- tabloyu sil
ALTER TABLE ISIMLER ADD TELEFON VARCHAR(12) -- kolon ekleme
ALTER TABLE ISIMLER ADD SOYISIM VARCHAR(12) -- kolon ekleme
ALTER TABLE ISIMLER DROP COLUMN SOYISIM -- kolon sil
ALTER TABLE ISIMLER ALTER COLUMN TELEFON VARCHAR(50) -- varolan bir kolonun içeriğini değiştirme
TRUNCATE TABLE ISIMLER -- tablonun içerisindeki verileri siler
---------------------------------------------------------------------------
DECLARE @ISIM AS VARCHAR(100) -- değişken tanımlama
SET @ISIM='MEHMET' -- değişkene değer atama
DECLARE @SOYISIM AS VARCHAR(100)='DEMİREL' -- değişken tanımlama ve değişkene değer atama
SELECT @ISIM -- görüntüleme
SELECT @SOYISIM -- görüntüleme

--DECLARE 
--@SAYI1 AS INTEGER,
--@SAYI2 AS INTEGER,
--@SAYI3 AS INTEGER
-- OR --
DECLARE @SAYI1 AS INTEGER=10
DECLARE @SAYI2 AS INTEGER
SET @SAYI2='20'
DECLARE @TOPLAM2 AS INTEGER
SET @TOPLAM2=@SAYI1+@SAYI2
SELECT @SAYI1 AS SAYI1,@SAYI2 AS SAYI2,@SAYI1+@SAYI2 AS TOPLAM,@TOPLAM2 AS TOPLAM2 -- alias
-- TABLODAKİ DEĞERLERİ DEĞİŞKENE ATAMA --
DECLARE @ISIM AS VARCHAR(20)
DECLARE @TELEFON AS VARCHAR(20)
SELECT 
@ISIM=ISIM,@TELEFON=TELEFON FROM ISIMLER WHERE ID=1
SELECT @ISIM,@TELEFON
-- DATE TIME --
DECLARE @DATE AS DATETIME
SET @DATE=GETDATE()
SELECT @DATE TARIH
-- String functions --
-- SUBSTRING --
DECLARE @KELIME AS VARCHAR(50)
SET @KELIME='MERHABA DÜNYA'
SELECT SUBSTRING(@KELIME,1,7) -- BELİRLENMİŞ İNDEKSLER ARASI CHARLARI AYIRIR
SELECT SUBSTRING(@KELIME,9,13)
-- LOWER, UPPER --
DECLARE @KELIME AS VARCHAR(50)
SET @KELIME='MERHABA DÜNYA'
SELECT LOWER(@KELIME) -- KELİMELERİN HEPSİNİ BÜYÜK HARF YAPAR
SELECT UPPER(@KELIME) -- KELİMELERİN HEPSİNİ KÜÇÜK HARF YAPAR
-- String birleştirme --
DECLARE @AD AS VARCHAR(50)='MEHMET'
DECLARE @SOYAD AS VARCHAR(50)='DEMİREL'
SELECT @AD+' '+@SOYAD
-- RIGHT, LEFT --
DECLARE @KELIME AS VARCHAR(50)
SET @KELIME='MERHABA DÜNYA'
SELECT LEFT(@KELIME,7) -- SOLDAN İTİBAREN 7 KARAKTER
SELECT RIGHT(@KELIME,5) -- SAĞDAN İTİBAREN 5 KARAKTER
-- LTRIM,RTRIM,TRIM --
DECLARE @KELIME AS VARCHAR(100)='   MERHABA DÜNYA   '
SELECT LTRIM(@KELIME) -- SOL KISIMDAKI BOŞLUKLARI SİLER
SELECT RTRIM(@KELIME) -- SAĞ KISIMDAKİ BOŞLUKLARI SİLER
SELECT TRIM(@KELIME) -- SAĞ VE SOLDAKİ BOŞLUKLARI SİLER
SELECT LTRIM(RTRIM(@KELIME)) -- TRIM İLE AYNI
-- REPLACE --
DECLARE @KELIME AS VARCHAR(100)='MERHABA DÜNYA'
SELECT REPLACE(@KELIME,'Ü','U') -- HARF DEĞİŞİMİ
REPLACE(@KELIME,'MERHABA','HELLO') -- KELIME DEĞİŞİMİ
SELECT REPLACE(REPLACE(@KELIME,'MERHABA','HELLO'),'DÜNYA','WORLD')
-- LEN --
DECLARE @KELIME AS VARCHAR(100)='MERHABA DÜNYA'
SELECT LEN(@KELIME) -- CÜMLE VEYA KELIME UZUNLUGU
-- STRING_SPLIT --
DECLARE @KELIME AS VARCHAR(100)='MERHABA DÜNYA'
SELECT
* FROM string_split(@KELIME,' ') -- KELIMELERI TABLO DEĞERİNE DÖNÜŞTÜRÜR
DECLARE @KELIME AS VARCHAR(100)='MERHABA BEN MEHMET SQL EĞİTİMİ ALIYORUM'
SELECT
* FROM string_split(@KELIME,' ')
